version: "3.9"
services:

  db:
    image: 'postgres:14'
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
      # - ./data:/data
    env_file:
      - ./.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      # THIS IS UNSAFE!
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432

  pgadmin:
    image: 'dpage/pgadmin4'
    volumes:
      - pgadmin:/var/lib/pgadmin
      # - ./environment/db_servers.json:/pgadmin4/servers.json
    env_file:
      - ./.env
    ports:
      - 5050:5050

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    links:
      - db:db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app?sslmode=disable
    depends_on:
      - db

volumes:
  app-db-data:
  # ms-db-data:
  pgadmin:
